### ISSUE TITLE
Custom Rewards are not in sync

### ISSUE THREAD

**Issue by acouvreur** [acouvreur/twitch-channel-points-hackathon#6]
Some custom rewards are left after deletion

Which causes an error on redemption : 

Unhandled Promise Rejection
TypeError: Cannot read property 'onRedemption' of undefined
    at PubSubListener.onRedemptionEventReceived [as _callback] (C:/Users//AppData/Local/Programs/twitch-channel-points-hackathon/resources/app.asar/node_modules/backend/src/pub-sub/redemption-event.handler.js:40:27)
    at PubSubListener.call (C:/Users//AppData/Local/Programs/twitch-channel-points-hackathon/resources/app.asar/node_modules/backend/node_modules/twitch-pubsub-client/lib/PubSubListener.js:50:14)
    at SingleUserPubSubClient.<anonymous> (C:/Users//AppData/Local/Programs/twitch-channel-points-hackathon/resources/app.asar/node_modules/backend/node_modules/twitch-pubsub-client/lib/SingleUserPubSubClient.js:54:50)
    at step (C:/Users//AppData/Local/Programs/twitch-channel-points-hackathon/resources/app.asar/node_modules/backend/node_modules/tslib/tslib.js:143:27)
    at Object.next (C:/Users//AppData/Local/Programs/twitch-channel-points-hackathon/resources/app.asar/node_modules/backend/node_modules/tslib/tslib.js:124:57)
    at fulfilled (C:/Users//AppData/Local/Programs/twitch-channel-points-hackathon/resources/app.asar/node_modules/backend/node_modules/tslib/tslib.js:114:62)

**Comment by acouvreur** [comment]
Won't fix ?
